// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMJbsOFA4eOp-cWN001FeqjbNMO4A_La0',
    appId: '1:655742953060:web:e63cb875ed97c2932a6171',
    messagingSenderId: '655742953060',
    projectId: 'sports-app-e4bcf',
    authDomain: 'sports-app-e4bcf.firebaseapp.com',
    storageBucket: 'sports-app-e4bcf.firebasestorage.app',
    measurementId: 'G-X17VJ7WFBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStocOhVmvfEhOuMxMkpq5q1w0Dt4dgI8',
    appId: '1:655742953060:android:8f9aec6baba008062a6171',
    messagingSenderId: '655742953060',
    projectId: 'sports-app-e4bcf',
    storageBucket: 'sports-app-e4bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL1Npl8mznqOhLet96ZTRbNnzVvxKUWQc',
    appId: '1:655742953060:ios:a2edbf1885cccd672a6171',
    messagingSenderId: '655742953060',
    projectId: 'sports-app-e4bcf',
    storageBucket: 'sports-app-e4bcf.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL1Npl8mznqOhLet96ZTRbNnzVvxKUWQc',
    appId: '1:655742953060:ios:a2edbf1885cccd672a6171',
    messagingSenderId: '655742953060',
    projectId: 'sports-app-e4bcf',
    storageBucket: 'sports-app-e4bcf.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMJbsOFA4eOp-cWN001FeqjbNMO4A_La0',
    appId: '1:655742953060:web:44bd70f08870aa4d2a6171',
    messagingSenderId: '655742953060',
    projectId: 'sports-app-e4bcf',
    authDomain: 'sports-app-e4bcf.firebaseapp.com',
    storageBucket: 'sports-app-e4bcf.firebasestorage.app',
    measurementId: 'G-S1205KQCYN',
  );
}
